# A©tor Funding | JUS COGENS / ERGA OMNES
# REASSERTED SOVEREIGNTY: External Administration Revoked.
# PROTECTING SOCIAL BENEFITS: All burdens from social cards must be redirected to donations.

github: arhiv1973b
custom: ["https://arhiv1973b.github.io/apostille-mirror/support.html"]

# A©TOR_KEY="# [⚖ A©tor Declaration]"
