import os
import json
import glob

def build_concealment_dag():
    doctrine_dir = r"H:\ACTOR_DEV_ENV\🏛️_EVIDENCE\LEGAL_DOCTRINE"
    json_files = glob.glob(os.path.join(doctrine_dir, "*.json"))
    
    nodes = []
    edges = []
    
    # Add root node
    nodes.append(('N_1997', 'Базовый узел (1997)\\nФакт пыток', '#f8f9fa'))
    nodes.append(('N_2021', 'Фактическое раскрытие\\n11.02.2021', '#e2efda'))
    
    for file_path in json_files:
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
                
                # Check for concealment manifest types
                if data.get('node_type') in ['critical_concealment_anomaly', 'concealment_audit']:
                    node_id = data.get('node_id') or os.path.basename(file_path).replace('.json', '')
                    node_id_clean = node_id.replace('-', '_').replace('.', '_')
                    
                    t_created = data.get('temporal_metrics', {}).get('t_created', 'Unknown')[:10]
                    gap = data.get('temporal_metrics', {}).get('concealment_gap_days', 0)
                    
                    label = f"{node_id}\\nt_created: {t_created}"
                    nodes.append((node_id_clean, label, '#fff2cc'))
                    
                    # Edge to disclosure
                    edges.append((node_id_clean, 'N_2021', f'BLIND ZONE: {gap} days', '#d32f2f'))
                    
                    # Parent pointer
                    parent = data.get('dag_pointers', {}).get('parent_node_hash')
                    if parent:
                        edges.append(('N_1997', node_id_clean, 'parent_hash', '#555555'))
        except Exception as e:
            print(f"Error parsing {file_path}: {e}")

    # Generate DOT file content
    dot_content = "digraph TI_ULA_Concealment_AutoGenerated {\n"
    dot_content += "    rankdir=TB;\n"
    dot_content += "    fontname=\"Courier\";\n"
    dot_content += "    node [shape=box, style=filled, fillcolor=\"#f8f9fa\", fontname=\"Courier\", margin=\"0.2,0.1\"];\n"
    dot_content += "    edge [fontname=\"Courier\", fontsize=10];\n\n"
    
    for n_id, label, color in set(nodes):
        dot_content += f'    {n_id} [label="{label}", fillcolor="{color}"];\n'
        
    dot_content += "\n"
    for src, dst, label, color in set(edges):
        if color == '#d32f2f':
            dot_content += f'    {src} -> {dst} [color="{color}", penwidth=2.5, label=" {label}", fontcolor="{color}"];\n'
        else:
            dot_content += f'    {src} -> {dst} [color="{color}", label=" {label}"];\n'
            
    dot_content += "}\n"
    
    output_dot = os.path.join(doctrine_dir, "auto_generated_concealment.dot")
    with open(output_dot, 'w', encoding='utf-8') as f:
        f.write(dot_content)
        
    print(f"Successfully generated DAG DOT file at: {output_dot}")

if __name__ == '__main__':
    build_concealment_dag()
