services:
  actor-app-dev:
    build: .
    user: "0:0"
    volumes:
      - audit_data:/app/.audit
  actor-audit:
    image: anchore/grype:latest
    depends_on:
      - actor-app-dev
    volumes:
      - audit_data:/app:ro
    environment:
      - GRYPE_DB_AUTO_UPDATE=false
    # Прямой вызов, без оболочки sh
    entrypoint: ["grype", "/app", "-o", "table"]

volumes:
  audit_data:
