# vclt_legal_api.py
"""Simple legal API for VCLT articles.
Provides a function `get_article_text(article_number)` that reads the JSON index
`vclt_index.json` (generated by `legal_indexer.py`) and returns the article content.
"""
import json
import pathlib

BASE_DIR = pathlib.Path(__file__).parent.resolve()
INDEX_FILE = BASE_DIR / "vclt_index.json"

def get_article_text(article_number):
    """Return the text of the requested article.
    Parameters
    ----------
    article_number : int or str
        Article number (e.g., 60 or "60").
    Returns
    -------
    str
        Full article text if found, otherwise a not‑found message.
    """
    if not INDEX_FILE.exists():
        return "Source not indexed."
    try:
        with open(INDEX_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
        key = str(article_number)
        article = data.get(key)
        if not article:
            return "Article not found."
        title = article.get("title", "")
        content = article.get("content", "")
        return f"{title}\n{content}".strip()
    except Exception as e:
        return f"Error reading index: {e}"

if __name__ == "__main__":
    print(get_article_text(60))