server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-Actor-Case "CASE-MACHERET-1997-2026";
    add_header X-Actor-IDNP "2000001159655";
    
    # Кэш для статики
    location ~* \.(css|js|json|png|jpg|ico)$ {
        expires 1d;
        add_header Cache-Control "public, immutable";
    }
    
    location / {
        try_files $uri $uri/ $uri.html =404;
    }
    
    # 404 страница
    error_page 404 /index.html;
}
