import matplotlib
matplotlib.use('Agg')  # Блокировка попыток открыть окно (Fix для WSL)
import matplotlib.pyplot as plt

# Данные аудита Сектора 9
nodes = ["ROOT_JC", "IMWM44", "DR4Y15 (TOXIC)", "DLTP7B", "4J20E9"]
delays = [0, 14, 6363, 0, 0]
colors = ['#00f2ff', '#00f2ff', '#ff003c', '#00f2ff', '#00f2ff']

plt.figure(figsize=(10, 6))
plt.style.use('dark_background')

# Построение гистограммы
bars = plt.bar(nodes, delays, color=colors, edgecolor='white', linewidth=0.5)

# Настройка эстетики Сектора 9
plt.title('SECTOR 9: TEMPORAL ANOMALY MAP (CASE-MACHERET)', color='#00f2ff', fontsize=14)
plt.ylabel('Days of Delay (Procedural Vacuum)', color='#e0e0e0')
plt.xlabel('Verification Nodes', color='#e0e0e0')
plt.grid(axis='y', linestyle='--', alpha=0.3)

# Добавление текстового значения над "токсичным" узлом
plt.text(2, 6363 + 100, '6363 DAYS', ha='center', color='#ff003c', fontweight='bold')

# Подпись администратора
plt.figtext(0.5, 0.01, "Generated by A©tor Admin | Verified via Jus Cogens Protocol",
            ha="center", fontsize=8, bbox={"facecolor":"orange", "alpha":0.2, "pad":5})

plt.tight_layout()
plt.savefig('sector9_toxicity_map.png')
print("--- [A©tōr] Карта токсичности успешно сгенерирована: sector9_toxicity_map.png ---")
